export const cards = [
  {
    id: "1",
    title: "The chicken is going to live",
    options: [
      { votes: 10, name: "option_1" },
      { votes: 12, name: "option_2" },
      { votes: 20, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "1",
    max: 100,
    active: false,
  },
  {
    id: "2",
    title: "This is a vote",
    options: [
      { votes: 10, name: "option_1" },
      { votes: 12, name: "option_2" },
      { votes: 20, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "2",
    max: 100,
    active: true,
  },
  {
    id: "3",
    title: "Different vote",
    options: [
      { votes: 10, name: "option_1" },
      { votes: 12, name: "option_2" },
      { votes: 20, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "2",
    max: 100,
    active: true,
  },
  {
    id: "4",
    title: "The chicken is going to live",
    options: [
      { votes: 10, name: "option_1" },
      { votes: 12, name: "option_2" },
      { votes: 20, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "1",
    max: 100,
    active: true,
  },
  {
    id: "5",
    title: "The chicken is going to live",
    options: [
      { votes: 10, name: "option_1" },
      { votes: 12, name: "option_2" },
      { votes: 20, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "3",
    max: 100,
    active: false,
  },
];
