export const cards = [
  {
    id: "1",
    title: "The chicken is going to live",
    options: [
      { id: 1, votes: 10, selected: true, name: "option_1" },
      { id: 2, votes: 12, selected: false, name: "option_2" },
      { id: 3, votes: 20, selected: false, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "1",
    max: 100,
    active: false,
    winner: "option_2",
    voted: true,
  },
  {
    id: "2",
    title: "This is a vote",
    options: [
      { id: 1, votes: 10, selected: true, name: "option_1" },
      { id: 2, votes: 12, selected: false, name: "option_2" },
      { id: 3, votes: 20, selected: false, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "2",
    max: 100,
    active: true,
    winner: "option_1",
    voted: true,
  },
  {
    id: "3",
    title: "Different vote",
    options: [
      { id: 1, votes: 10, selected: true, name: "option_1" },
      { id: 2, votes: 12, selected: false, name: "option_2" },
      { id: 3, votes: 20, selected: false, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "2",
    max: 100,
    active: true,
    winner: "option_2",
    voted: true,
  },
  {
    id: "4",
    title: "The chicken is going to live",
    options: [
      { id: 1, votes: 10, selected: true, name: "option_1" },
      { id: 2, votes: 12, selected: false, name: "option_2" },
      { id: 3, votes: 20, selected: false, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "1",
    max: 100,
    active: true,
    winner: "option_1",
    voted: true,
  },
  {
    id: "5",
    title: "The chicken is going to live",
    options: [
      { id: 1, votes: 10, selected: true, name: "option_1" },
      { id: 2, votes: 12, selected: false, name: "option_2" },
      { id: 3, votes: 20, selected: false, name: "option_3" },
    ],
    timeLeft: "00:05",
    creator_id: "3",
    max: 100,
    active: false,
    winner: "option_1",
    voted: true,
  },
];
