export const cards = [
  {
    id: "1",
    title: "The chicken is going to live",
    nVotesYay: 30,
    nVotesNay: 10,
    nVotesNeutral: 2,
    capacity: 50,
    passing_vote_req: 25,
    creator_id: "1",
    passed: true,
    active: false,
  },
  {
    id: "2",
    title: "The 2 is going to live",
    nVotesYay: 30,
    nVotesNay: 10,
    nVotesNeutral: 2,
    capacity: 50,

    passing_vote_req: 25,
    creator_id: "2",
    passed: true,
    active: false,
  },
  {
    id: "3",
    title: "The 3 is going to live",
    nVotesYay: 30,
    nVotesNay: 10,
    nVotesNeutral: 2,
    capacity: 50,

    passing_vote_req: 25,
    creator_id: "1",
    passed: true,
    active: true,
  },
  {
    id: "4",
    title: "The 4 is going to live",
    nVotesYay: 30,
    nVotesNay: 10,
    nVotesNeutral: 2,
    capacity: 50,

    passing_vote_req: 25,
    creator_id: "1",
    passed: false,
    active: false,
  },
  {
    id: "5",
    title: "The 5 is going to live",
    nVotesYay: 30,
    nVotesNay: 10,
    nVotesNeutral: 2,
    capacity: 50,

    passing_vote_req: 25,
    creator_id: "2",
    passed: true,
    active: true,
  },
];
